# Copyright (c) 2025 Przemyslaw Patrick Socha

"""
Settings UI for ESP32-S3 CircuitPython
Touch-based configuration for rotation, joystick type, and GPIO pins.
"""

import time

from code import (
    rgb565,
    draw_text,
    text_pixel_width,
    Button,
    BG_COLOR,
    BUTTON_COLOR,
    BUTTON_PRESSED_COLOR,
    TEXT_COLOR,
    BORDER_COLOR,
    FONT_16x16,
    CHAR_WIDTH_16x16,
    CHAR_HEIGHT_16x16,
)

# Screen dimensions
SCREEN_W = 600

# Layout constants
LABEL_X = 30
TOGGLE_X = 200
BTN_H = 32
SMALL_BTN_W = 36
PIN_DISPLAY_W = 48

# GPIO pin row layout
PIN_LABEL_X = 30
PIN_MINUS_X = 200
PIN_VALUE_X = PIN_MINUS_X + SMALL_BTN_W + 6
PIN_PLUS_X = PIN_VALUE_X + PIN_DISPLAY_W + 6

PIN_KEYS = ("up", "down", "left", "right", "center")
PIN_LABELS = ("UP", "DOWN", "LEFT", "RIGHT", "CENTER")
MAX_PIN = 48


def save_settings(rotation, joystick_type, gpio_pins):
    """Write settings.py to flash filesystem."""
    content = (
        "# Device settings - auto-generated by settings UI\n"
        f"rotation = {rotation}\n"
        f'joystick_type = "{joystick_type}"\n'
        "gpio_pins = {\n"
    )
    for key in ("up", "down", "left", "right", "center"):
        val = gpio_pins[key]
        content += f'    "{key}": {val},\n'
    content += "}\n"
    with open("settings.py", "w") as f:
        f.write(content)


def load_current_settings():
    """Load current settings from settings.py, return defaults on failure."""
    rotation = 0
    joystick_type = "i2c"
    gpio_pins = {"up": None, "down": None, "left": None, "right": None, "center": None}
    try:
        import sys
        if "settings" in sys.modules:
            del sys.modules["settings"]
        import settings
        rotation = getattr(settings, "rotation", 0)
        joystick_type = getattr(settings, "joystick_type", "i2c")
        pins = getattr(settings, "gpio_pins", None)
        if pins:
            for k in PIN_KEYS:
                if k in pins:
                    gpio_pins[k] = pins[k]
    except ImportError:
        pass
    return rotation, joystick_type, gpio_pins


def format_pin(val):
    """Format a pin value for display: None -> '--', int -> zero-padded."""
    if val is None:
        return "--"
    return f"{val:02d}"


def draw_label(display, text, x, y):
    """Draw a left-aligned label at the given position."""
    draw_text(display, text, x, y + (BTN_H - CHAR_HEIGHT_16x16) // 2, TEXT_COLOR)


def draw_pin_value(display, val, x, y):
    """Draw the pin value in a box."""
    # Clear the value area
    display.fill_rect(x, y, PIN_DISPLAY_W, BTN_H, BG_COLOR)
    # Draw border
    display.fill_rect(x, y, PIN_DISPLAY_W, 2, BORDER_COLOR)
    display.fill_rect(x, y + BTN_H - 2, PIN_DISPLAY_W, 2, BORDER_COLOR)
    display.fill_rect(x, y, 2, BTN_H, BORDER_COLOR)
    display.fill_rect(x + PIN_DISPLAY_W - 2, y, 2, BTN_H, BORDER_COLOR)
    # Draw text centered
    txt = format_pin(val)
    tw = text_pixel_width(txt)
    tx = x + (PIN_DISPLAY_W - tw) // 2
    ty = y + (BTN_H - CHAR_HEIGHT_16x16) // 2
    draw_text(display, txt, tx, ty, TEXT_COLOR)


def draw_full_screen(display, rotation, joystick_type, gpio_pins,
                     btn_rot_0, btn_rot_180, btn_i2c, btn_gpio,
                     pin_minus_btns, pin_plus_btns,
                     btn_save, btn_cancel):
    """Draw the complete settings UI."""
    display.fill_color(BG_COLOR)

    # Title
    title = "SETTINGS"
    tw = text_pixel_width(title)
    draw_text(display, title, (SCREEN_W - tw) // 2, 25, TEXT_COLOR)

    # Rotation row (y=70)
    draw_label(display, "Rotation", LABEL_X, 70)
    color_0 = BUTTON_PRESSED_COLOR if rotation == 0 else BUTTON_COLOR
    color_180 = BUTTON_PRESSED_COLOR if rotation == 180 else BUTTON_COLOR
    btn_rot_0.draw(display, color_0)
    btn_rot_180.draw(display, color_180)

    # Joystick row (y=120)
    draw_label(display, "Joystick", LABEL_X, 120)
    color_i2c = BUTTON_PRESSED_COLOR if joystick_type == "i2c" else BUTTON_COLOR
    color_gpio = BUTTON_PRESSED_COLOR if joystick_type == "gpio" else BUTTON_COLOR
    btn_i2c.draw(display, color_i2c)
    btn_gpio.draw(display, color_gpio)

    # GPIO pins (only when gpio selected)
    if joystick_type == "gpio":
        draw_gpio_rows(display, gpio_pins, pin_minus_btns, pin_plus_btns)

    # Save / Cancel
    btn_save.draw(display)
    btn_cancel.draw(display)

    display.swap_buffers()


def draw_gpio_rows(display, gpio_pins, pin_minus_btns, pin_plus_btns):
    """Draw all GPIO pin configuration rows."""
    for i, key in enumerate(PIN_KEYS):
        y = 170 + i * 40
        draw_label(display, PIN_LABELS[i], PIN_LABEL_X, y)
        pin_minus_btns[i].draw(display)
        draw_pin_value(display, gpio_pins[key], PIN_VALUE_X, y)
        pin_plus_btns[i].draw(display)


def main(display, touch):
    """Settings UI entry point. Returns dict with settings and saved flag."""

    # Load current settings
    rotation, joystick_type, gpio_pins = load_current_settings()

    # --- Create buttons ---

    # Rotation toggles (y=70)
    toggle_w = 64
    toggle_gap = 12
    btn_rot_0 = Button(TOGGLE_X, 70, toggle_w, BTN_H, "0")
    btn_rot_180 = Button(TOGGLE_X + toggle_w + toggle_gap, 70, toggle_w, BTN_H, "180")

    # Joystick toggles (y=120)
    btn_i2c = Button(TOGGLE_X, 120, toggle_w, BTN_H, "I2C")
    btn_gpio = Button(TOGGLE_X + toggle_w + toggle_gap, 120, toggle_w, BTN_H, "GPIO")

    # GPIO pin +/- buttons
    pin_minus_btns = []
    pin_plus_btns = []
    for i in range(5):
        y = 170 + i * 40
        pin_minus_btns.append(Button(PIN_MINUS_X, y, SMALL_BTN_W, BTN_H, "-"))
        pin_plus_btns.append(Button(PIN_PLUS_X, y, SMALL_BTN_W, BTN_H, "+"))

    # Save / Cancel (y=390)
    btn_save = Button(30, 390, 100, BTN_H + 8, "SAVE")
    btn_cancel = Button(SCREEN_W - 130, 390, 100, BTN_H + 8, "CANCEL")

    # --- Initial draw ---
    draw_full_screen(display, rotation, joystick_type, gpio_pins,
                     btn_rot_0, btn_rot_180, btn_i2c, btn_gpio,
                     pin_minus_btns, pin_plus_btns,
                     btn_save, btn_cancel)

    # --- Touch loop ---
    while True:
        touch_point = touch.get_touch()

        if touch_point:
            x, y = touch_point
            redraw_all = False
            pin_changed = -1

            # Rotation toggles
            if btn_rot_0.contains(x, y):
                rotation = 0
                redraw_all = True
            elif btn_rot_180.contains(x, y):
                rotation = 180
                redraw_all = True

            # Joystick toggles
            elif btn_i2c.contains(x, y):
                if joystick_type != "i2c":
                    joystick_type = "i2c"
                    redraw_all = True
            elif btn_gpio.contains(x, y):
                if joystick_type != "gpio":
                    joystick_type = "gpio"
                    redraw_all = True

            # GPIO pin buttons (only active when gpio selected)
            elif joystick_type == "gpio":
                for i in range(5):
                    key = PIN_KEYS[i]
                    if pin_minus_btns[i].contains(x, y):
                        val = gpio_pins[key]
                        if val is None:
                            pass  # already at minimum
                        elif val == 0:
                            gpio_pins[key] = None
                        else:
                            gpio_pins[key] = val - 1
                        pin_changed = i
                        break
                    elif pin_plus_btns[i].contains(x, y):
                        val = gpio_pins[key]
                        if val is None:
                            gpio_pins[key] = 0
                        elif val < MAX_PIN:
                            gpio_pins[key] = val + 1
                        pin_changed = i
                        break

            # Save
            if btn_save.contains(x, y):
                btn_save.draw(display, BUTTON_PRESSED_COLOR)
                display.swap_buffers()
                time.sleep(0.15)
                save_settings(rotation, joystick_type, gpio_pins)
                return {
                    "rotation": rotation,
                    "joystick_type": joystick_type,
                    "gpio_pins": gpio_pins,
                    "saved": True,
                }

            # Cancel
            if btn_cancel.contains(x, y):
                btn_cancel.draw(display, BUTTON_PRESSED_COLOR)
                display.swap_buffers()
                time.sleep(0.15)
                return {"saved": False}

            # Apply redraws
            if redraw_all:
                draw_full_screen(display, rotation, joystick_type, gpio_pins,
                                 btn_rot_0, btn_rot_180, btn_i2c, btn_gpio,
                                 pin_minus_btns, pin_plus_btns,
                                 btn_save, btn_cancel)
            elif pin_changed >= 0:
                # Only redraw the changed pin value
                key = PIN_KEYS[pin_changed]
                py = 170 + pin_changed * 40
                draw_pin_value(display, gpio_pins[key], PIN_VALUE_X, py)
                display.swap_buffers()

        time.sleep(0.05)
