# Copyright (c) 2025 Przemyslaw Patrick Socha

"""
Settings UI for ESP32-S3 CircuitPython
Touch-based configuration for rotation, joystick type, GPIO pins, and extra buttons.
Interactive GPIO scanning - press a physical button to assign its pin.
"""

import time

from code import (
    rgb565,
    draw_text,
    text_pixel_width,
    Button,
    BG_COLOR,
    BUTTON_COLOR,
    BUTTON_PRESSED_COLOR,
    TEXT_COLOR,
    BORDER_COLOR,
    FONT_16x16,
    CHAR_WIDTH_16x16,
    CHAR_HEIGHT_16x16,
)

# Screen dimensions
SCREEN_W = 600

# Available GPIO pins (no external resistors - use internal pull-up)
VALID_PINS = (1, 7, 8, 18, 38, 39, 40, 41, 42, 45, 46)

# Joystick directions
JOYSTICK_KEYS = ("up", "down", "left", "right", "center")
JOYSTICK_LABELS = ("UP", "DOWN", "LEFT", "RIGHT", "CENTER")
JOYSTICK_SHORT = ("U", "D", "L", "R", "C")

# Extra buttons
BUTTON_KEYS = ("btn_a", "btn_b", "btn_c", "btn_d")
BUTTON_LABELS = ("BTN A", "BTN B", "BTN C", "BTN D")
BUTTON_SHORT = ("A", "B", "C", "D")

# Layout
LABEL_X = 30
TOGGLE_X = 200
BTN_H = 32
SETUP_BTN_X = 470
SETUP_BTN_W = 100

# Extra colors
SECTION_COLOR = rgb565(100, 200, 255)
HINT_COLOR = rgb565(130, 130, 130)
DETECTED_COLOR = rgb565(0, 255, 100)


def save_settings(rotation, joystick_type, gpio_pins, extra_buttons):
    """Write settings.py to flash filesystem."""
    content = "# Device settings - auto-generated by settings UI\n"
    content += "rotation = " + str(rotation) + "\n"
    content += 'joystick_type = "' + joystick_type + '"\n'
    content += "gpio_pins = {\n"
    for key in JOYSTICK_KEYS:
        val = gpio_pins.get(key)
        content += '    "' + key + '": ' + str(val) + ",\n"
    content += "}\n"
    content += "extra_buttons = {\n"
    for key in BUTTON_KEYS:
        val = extra_buttons.get(key)
        content += '    "' + key + '": ' + str(val) + ",\n"
    content += "}\n"
    with open("settings.py", "w") as f:
        f.write(content)


def load_current_settings():
    """Load current settings from settings.py, return defaults on failure."""
    rotation = 0
    joystick_type = "i2c"
    gpio_pins = {k: None for k in JOYSTICK_KEYS}
    extra_buttons = {k: None for k in BUTTON_KEYS}
    try:
        import sys
        if "settings" in sys.modules:
            del sys.modules["settings"]
        import settings
        rotation = getattr(settings, "rotation", 0)
        joystick_type = getattr(settings, "joystick_type", "i2c")
        pins = getattr(settings, "gpio_pins", None)
        if pins:
            for k in JOYSTICK_KEYS:
                if k in pins:
                    gpio_pins[k] = pins[k]
        btns = getattr(settings, "extra_buttons", None)
        if btns:
            for k in BUTTON_KEYS:
                if k in btns:
                    extra_buttons[k] = btns[k]
    except ImportError:
        pass
    return rotation, joystick_type, gpio_pins, extra_buttons


def format_pin(val):
    """Format a pin value for display: None -> '--', int -> zero-padded."""
    if val is None:
        return "--"
    return f"{val:02d}"


def pin_summary(pins, keys, short_labels):
    """Build compact summary like 'U:07 D:08 L:-- R:-- C:--'."""
    parts = []
    for key, lbl in zip(keys, short_labels):
        parts.append(lbl + ":" + format_pin(pins.get(key)))
    return " ".join(parts)


def draw_centered(display, text, y, color):
    """Draw text centered horizontally."""
    tw = text_pixel_width(text)
    draw_text(display, text, (SCREEN_W - tw) // 2, y, color)


def draw_label(display, text, x, y, color=TEXT_COLOR):
    """Draw a left-aligned label vertically centered in a BTN_H row."""
    draw_text(display, text, x, y + (BTN_H - CHAR_HEIGHT_16x16) // 2, color)


# --- Interactive GPIO scanning ---


def scan_gpio_pin(display, touch, prompt, exclude):
    """Monitor VALID_PINS for a button press. Returns pin number or None if skipped.

    Configures available pins with internal pull-up (no external resistors).
    Detects active-LOW press with debounce.
    """
    import digitalio
    import microcontroller

    # Draw scan overlay
    display.fill_color(BG_COLOR)
    draw_centered(display, "GPIO SETUP", 80, SECTION_COLOR)
    draw_centered(display, "Press " + prompt, 190, TEXT_COLOR)
    draw_centered(display, "touch SKIP to leave empty", 260, HINT_COLOR)

    skip_btn = Button(SCREEN_W // 2 - 60, 340, 120, 40, "SKIP")
    skip_btn.draw(display)
    display.swap_buffers()

    # Init all available pins with internal pull-up
    scan_pins = {}
    for pn in VALID_PINS:
        if pn in exclude:
            continue
        try:
            dio = digitalio.DigitalInOut(getattr(microcontroller.pin, "GPIO" + str(pn)))
            dio.direction = digitalio.Direction.INPUT
            dio.pull = digitalio.Pull.UP
            scan_pins[pn] = dio
        except (ValueError, RuntimeError):
            pass

    if not scan_pins:
        display.fill_color(BG_COLOR)
        draw_centered(display, "No pins available!", 200, rgb565(255, 100, 100))
        display.swap_buffers()
        time.sleep(1.5)
        return None

    result = None
    try:
        while True:
            # Check touch for SKIP
            tp = touch.get_touch()
            if tp and skip_btn.contains(tp[0], tp[1]):
                break

            # Poll GPIO pins (active-LOW with debounce)
            for pn, dio in scan_pins.items():
                if not dio.value:
                    time.sleep(0.03)
                    if not dio.value:
                        result = pn
                        break
            if result is not None:
                # Show detection feedback
                display.fill_color(BG_COLOR)
                draw_centered(display, "GPIO SETUP", 80, SECTION_COLOR)
                txt = prompt + " = GPIO " + str(result)
                draw_centered(display, txt, 190, DETECTED_COLOR)
                display.swap_buffers()

                # Wait for button release before continuing
                dio = scan_pins[result]
                while not dio.value:
                    time.sleep(0.02)
                time.sleep(0.4)
                break

            time.sleep(0.02)
    finally:
        for dio in scan_pins.values():
            dio.deinit()

    return result


def run_scan_sequence(display, touch, keys, labels, exclude):
    """Run interactive scan for a sequence of GPIO assignments.

    Returns dict mapping keys to pin numbers (or None for skipped).
    Pins assigned earlier in the sequence are excluded from later prompts.
    """
    result = {}
    used = set(exclude)
    for key, label in zip(keys, labels):
        pin = scan_gpio_pin(display, touch, label, used)
        result[key] = pin
        if pin is not None:
            used.add(pin)
    return result


# --- Main settings screen ---


def draw_settings_screen(display, rotation, joystick_type, gpio_pins, extra_buttons,
                         btn_rot_0, btn_rot_180, btn_i2c, btn_gpio,
                         btn_setup_joy, btn_setup_btns, btn_save, btn_cancel):
    """Draw the complete settings screen."""
    display.fill_color(BG_COLOR)

    # Title
    draw_centered(display, "SETTINGS", 25, TEXT_COLOR)

    # Rotation row (y=70)
    draw_label(display, "Rotation", LABEL_X, 70)
    c0 = BUTTON_PRESSED_COLOR if rotation == 0 else BUTTON_COLOR
    c180 = BUTTON_PRESSED_COLOR if rotation == 180 else BUTTON_COLOR
    btn_rot_0.draw(display, c0)
    btn_rot_180.draw(display, c180)

    # Joystick type row (y=120)
    draw_label(display, "Joystick", LABEL_X, 120)
    ci = BUTTON_PRESSED_COLOR if joystick_type == "i2c" else BUTTON_COLOR
    cg = BUTTON_PRESSED_COLOR if joystick_type == "gpio" else BUTTON_COLOR
    btn_i2c.draw(display, ci)
    btn_gpio.draw(display, cg)

    # Joystick GPIO section (visible only when gpio selected)
    if joystick_type == "gpio":
        draw_label(display, "JOYSTICK PINS", LABEL_X, 175, SECTION_COLOR)
        btn_setup_joy.y = 175
        btn_setup_joy.draw(display)
        summary = pin_summary(gpio_pins, JOYSTICK_KEYS, JOYSTICK_SHORT)
        draw_text(display, summary, LABEL_X, 212, TEXT_COLOR)

    # Extra buttons section (always visible, shifts up when joystick is I2C)
    extra_y = 260 if joystick_type == "gpio" else 175
    draw_label(display, "EXTRA BUTTONS", LABEL_X, extra_y, SECTION_COLOR)
    btn_setup_btns.y = extra_y
    btn_setup_btns.draw(display)
    summary = pin_summary(extra_buttons, BUTTON_KEYS, BUTTON_SHORT)
    draw_text(display, summary, LABEL_X, extra_y + 37, TEXT_COLOR)

    # Save / Cancel
    btn_save.draw(display)
    btn_cancel.draw(display)

    display.swap_buffers()


def main(display, touch):
    """Settings UI entry point. Returns dict with settings and saved flag."""

    rotation, joystick_type, gpio_pins, extra_buttons = load_current_settings()

    # --- Create buttons ---
    toggle_w = 64
    toggle_gap = 12

    # Rotation toggles (y=70)
    btn_rot_0 = Button(TOGGLE_X, 70, toggle_w, BTN_H, "0")
    btn_rot_180 = Button(TOGGLE_X + toggle_w + toggle_gap, 70, toggle_w, BTN_H, "180")

    # Joystick type toggles (y=120)
    btn_i2c = Button(TOGGLE_X, 120, toggle_w, BTN_H, "I2C")
    btn_gpio = Button(TOGGLE_X + toggle_w + toggle_gap, 120, toggle_w, BTN_H, "GPIO")

    # Setup buttons (y repositioned dynamically in draw)
    btn_setup_joy = Button(SETUP_BTN_X, 175, SETUP_BTN_W, BTN_H, "SETUP")
    btn_setup_btns = Button(SETUP_BTN_X, 260, SETUP_BTN_W, BTN_H, "SETUP")

    # Save / Cancel (y=390)
    btn_save = Button(30, 390, 100, BTN_H + 8, "SAVE")
    btn_cancel = Button(SCREEN_W - 130, 390, 100, BTN_H + 8, "CANCEL")

    # --- Initial draw ---
    draw_settings_screen(display, rotation, joystick_type, gpio_pins, extra_buttons,
                         btn_rot_0, btn_rot_180, btn_i2c, btn_gpio,
                         btn_setup_joy, btn_setup_btns, btn_save, btn_cancel)

    # --- Touch loop ---
    while True:
        touch_point = touch.get_touch()

        if touch_point:
            x, y = touch_point
            redraw = False

            # Rotation toggles
            if btn_rot_0.contains(x, y):
                rotation = 0
                redraw = True
            elif btn_rot_180.contains(x, y):
                rotation = 180
                redraw = True

            # Joystick type toggles
            elif btn_i2c.contains(x, y):
                if joystick_type != "i2c":
                    joystick_type = "i2c"
                    redraw = True
            elif btn_gpio.contains(x, y):
                if joystick_type != "gpio":
                    joystick_type = "gpio"
                    redraw = True

            # Setup joystick GPIO pins (only when gpio selected)
            elif joystick_type == "gpio" and btn_setup_joy.contains(x, y):
                btn_setup_joy.draw(display, BUTTON_PRESSED_COLOR)
                display.swap_buffers()
                time.sleep(0.15)
                # Exclude pins already used by extra buttons
                exclude = set(v for v in extra_buttons.values() if v is not None)
                gpio_pins = run_scan_sequence(
                    display, touch, JOYSTICK_KEYS, JOYSTICK_LABELS, exclude
                )
                redraw = True

            # Setup extra buttons
            elif btn_setup_btns.contains(x, y):
                btn_setup_btns.draw(display, BUTTON_PRESSED_COLOR)
                display.swap_buffers()
                time.sleep(0.15)
                # Exclude pins already used by joystick (when gpio)
                exclude = set()
                if joystick_type == "gpio":
                    exclude = set(v for v in gpio_pins.values() if v is not None)
                extra_buttons = run_scan_sequence(
                    display, touch, BUTTON_KEYS, BUTTON_LABELS, exclude
                )
                redraw = True

            # Save
            elif btn_save.contains(x, y):
                btn_save.draw(display, BUTTON_PRESSED_COLOR)
                display.swap_buffers()
                time.sleep(0.15)
                save_settings(rotation, joystick_type, gpio_pins, extra_buttons)
                return {
                    "rotation": rotation,
                    "joystick_type": joystick_type,
                    "gpio_pins": gpio_pins,
                    "extra_buttons": extra_buttons,
                    "saved": True,
                }

            # Cancel
            elif btn_cancel.contains(x, y):
                btn_cancel.draw(display, BUTTON_PRESSED_COLOR)
                display.swap_buffers()
                time.sleep(0.15)
                return {"saved": False}

            if redraw:
                draw_settings_screen(
                    display, rotation, joystick_type, gpio_pins, extra_buttons,
                    btn_rot_0, btn_rot_180, btn_i2c, btn_gpio,
                    btn_setup_joy, btn_setup_btns, btn_save, btn_cancel,
                )

        time.sleep(0.05)
