# Device settings - auto-generated by settings UI
rotation = 0               # 0 or 180
joystick_type = "i2c"      # "i2c" or "gpio"
gpio_pins = {
    "up": None,
    "down": None,
    "left": None,
    "right": None,
    "center": None,
}
extra_buttons = {
    "btn_a": None,
    "btn_b": None,
    "btn_c": None,
    "btn_d": None,
}
